version: '3'

services:
    app:
        build:
            context: .
            dockerfile: ./compose/local/Dockerfile
        volumes:
            - .:/app
        ports:
            - "8000:8000"
